# -*- coding: utf-8 -*-
"""Day1_genai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10HW2jz5wNtmzzmNAM4nM5Agb1_GnxJ5m
"""

age=45
print(age)
print(type(age))

temp=-5
print(type(temp))

num=complex(10,4)
print(num)
print(type(num))

#none type
result=None
print(result)
print(type(result))

num=int(complex(10,4))
print(num)#not possible

#floor division
a=24.0
b=4.0
print("floor Division:",a//b)

a=24
b=4.0
print("floor Division:",a//b)

a=24.0
b=4
print("floor Division:",a//b)

#modulus
a=24
b=4
print("remainder:",a%b)

a=5+7j
b=5
sum=a+b
print(sum)

#comparison operator
a=20
b=15
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)

#logical operators
#and operator
username_valid=True
password_valid=True
print(username_valid and password_valid)

#or operator
username_valid=True
password_valid=False
print(username_valid or password_valid)

#not operator
is_blocked=False
print(not  is_blocked)

#bitwise operator
a=10
b=4
#and
print(a&b)

#or
a=10
b=4
print(a|b)

#xor
print(a^b)

#not
print(~a)

#left shift
print(a<<1)

#right shift
print(a>>1)

num=8
print(num<<2)
print(num>>2)

#membership opertor
#in operator
course="python"
print("P" in course)
print("y" in course)

#student example
student=["Rahul","Aman","Riya"]
print("Riya" in student)
print("Riya" not in student)

#identity operator
a=[1,2,3]
b=a
print(a is b)

a=[1,2,3]
b=a
print(a is not b)

#different objects
x=[1,2,3]
y=[1,2,3]
print(x is y)
print(x==y)

# student example
#operation precedence
#multiplication before addition
result=10+5*2
print(result)

result=(10+5)*2
print(result)

#multiple operator



"""module 5"""



# if statement
age=20
if age>=

#if elif else ladder
marks=82
if marks>=90:
  print("Grade A")
elif marks>=80:
  print("Grade B")
elif marks>=70:
  print("Grade C")
elif marks>=60:
  print("Grade D")
else:
  print("Grade E")

#ternary operator
age=22
result="eligible" if age>=18 else "Not Eligible"
print(result)

number=7
result="even " if number%2==0 else "odd"
print(result)

#match case
day=3
match day:
  case 1:
    print("Monday")
  case 2:
    print("Tuesday")
  case 3:
    print("Wednesday")
  case _:
      print("invalid day")

role="admin"

"""loops
#for loop
#while loop


"""

#for loop
#while loop
for i in range(1,10,0)# it from 1 to 9

for i in range(1,200,100):
    print(i)

for i in range(1,200,-5):
    print(i)

for charch

#nested loops
#number pattern
for i in range(3):
  for j in range(3):
    print(i,j)

#star pattern
for row in range(3):
  for col in range(3):
    print("*",end=" ")
print()

#infinite loop
#ex 1:
#while..true
#pass statement
for i in range(5):
  if i==3:
    pass
    print(i)

for i in range(1,6)

#enumerate function
#enumerate function provides both index and function
print(language[1])